apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clickhouse-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse
spec:
  selector:
    app: clickhouse
  ports:
    - port: 8123
      targetPort: 8123
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse
spec:
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      containers:
        - name: clickhouse
          image: clickhouse/clickhouse-server:23.3.8.21-alpine
          ports:
            - containerPort: 8123
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: CLICKHOUSE_USER
              value: clickhouse
            - name: CLICKHOUSE_PASSWORD
              value: clickhouse
          volumeMounts:
            - name: friend-alert-analytics-db
              mountPath: /var/lib/clickhouse/
      volumes:
        - name: friend-alert-analytics-db
          persistentVolumeClaim:
            claimName: clickhouse-pvc
